# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "mechanize", "~> 2.8"
gem "mail", "~> 2.7"
gem "dotenv", "~> 2.7"
gem "byebug", "~> 11.1"
